---
version: '2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:$ELASTIC_VERSION
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms800m -Xmx800m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1600m
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana-x-pack:$ELASTIC_VERSION
    links:
      - elasticsearch
    ports:
      - 5601:5601
    depends_on: ['elasticsearch']

  setup_filebeat:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    volumes: ['./setup-beat.sh:/usr/local/bin/setup-beat.sh:ro']
    command: /usr/local/bin/setup-beat.sh filebeat
    depends_on: ['kibana']

volumes:
  esdata1:
    driver: local
